### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by hacunamatada** [lxy5513/hrnet#1]
I ran the follow line:
python pose_estimation/video.py

Traceback (most recent call last):
  File "pose_estimation/video.py", line 28, in <module>
    from lib.detector.yolo.human_detector import main as yolo_det
ModuleNotFoundError: No module named 'lib.detector.yolo.human_detector'

how can i solve this problem?

**Comment by lciruelo** [comment]
same here
fatal: no submodule mapping found in .gitmodules for path 'lib/detector/yolo'

**Comment by thekoshkina** [comment]
same here

**Comment by lxy5513** [comment]
@hacunamatada 
Sorry , I see it just now, I already update the yolo moudle .   
by the way, maybe you can @me, when you occur some error in the project, so that I can know it as soon as possible, THX

**Comment by basicvisual** [comment]
Hi , i just dowloaded the repo and i still seem to have the issue , as mentioned above .  Do i have to do anything apart from what is mentioned in the readme ?

```
`python pose_estimation/demo.py 
Traceback (most recent call last):
  File "pose_estimation/demo.py", line 165, in <module>
    main()
  File "pose_estimation/demo.py", line 134, in main
    from lib.detector.yolo.human_detector import load_model as yolo_model
ModuleNotFoundError: No module named 'lib.detector.yolo.human_detector'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
`
```

**Comment by lxy5513** [comment]
@basicvisual  the problem have already fixed.

**Comment by lxy5513** [comment]
@basicvisual , you need configure env firstly, then download relative model

**Comment by basicvisual** [comment]
Thank you ! Could you tell me , where `2d keypoints (coco)[17 keypoints]` are returned for the video sequence. I  think it should be a `17x2` matrix right ?

**Comment by lxy5513** [comment]
In https://github.com/lxy5513/hrnet/blob/master/pose_estimation/demo.py#L153   
preds.shape = (N, 17, 2), N is  the frame number of video , 2 is the coordinate
 maxvals  = (N, 17, 1),  1 is the confidence of  coordinate
