### ISSUE TITLE
No module name utilitys ?

### ISSUE THREAD

**Issue by timtensor** [lxy5513/hrnet#11]
Hi I could successfully activate the enviroment and compile the library but i seem to have the following error 
```

env_info_file.yml) xt:~/hrnet-1$ python3.6 pose_estimation/video.py 
Traceback (most recent call last):
  File "pose_estimation/video.py", line 14, in <module>
    from utilitys import plot_keypoint, PreProcess
ModuleNotFoundError: No module named 'utilitys'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```
I have tried modifing the bash script but it did not help . 
I alsp seem to have problem other scripts as well . Atleast it does not complain about env issues

**Comment by lxy5513** [comment]
change utilitys to pose_utils

**Comment by timtensor** [comment]
Hi , thanks i have a few question. I come into the following error `mmd_detector` whihc leads to directly go to the `debugger` . As i understand there is still some work on going or ? The error code is below 

```
> /home/pramah/mvp/hrnet-1/lib/detector/mmdetection/high_api.py(6)<module>()
      5 import ipdb;ipdb.set_trace()
----> 6 import mmcv
      7 from mmcv.runner import load_checkpoint

```
Does it mean , i need to clone the `mmd_detector` into the root folder ? I was thinking to keep a issue tracker so that all known issues are tracked and new users can have it easier ?  I will make a summary after i succesuflly execute the installation and execution

**Comment by lxy5513** [comment]
Sorry, I will solve those bug and error in a few days.

**Comment by timtensor** [comment]
Thank you for your response. Pleae keep me posted of it  .

**Comment by lxy5513** [comment]
I update some thing and try 
`python pose_estimation/demo_mmd.py --display`   
`python pose_estimation/demo.py --display` 
  

It works.

**Comment by lxy5513** [comment]
```
 main_path = os.path.dirname(os.path.abspath(__file__)) + '/mmd'
 sys.path.insert(0, main_path)
```
in https://github.com/lxy5513/hrnet/blob/master/lib/detector/mmdetection/high_api.py#L3
because of this, you needn't clone to your root folder

**Comment by timtensor** [comment]
Hi i think i still get a lot of errors , I am using  python 3.6 , I just did the following way 
a) conda activate env_info_file.yml 
b) pip3 install -r requirements.txt ( to install all reuqirements)
c) cd lib && make ( successful) 
d) Made a folder models and created the following directory structure  `/hrnet/models/pytorch/pose_coco` where the pre trained model from HRnet is stored 
e) downloaded the `yolov3` weights in the folder `hrnet/lib/detector/yolo/yolov3.weights`
f)  Changed from `utilitys` to `pose_utils` as you had suggested 
g) ran the command ` python3.6 pose_estimation/video.py`

I was wondering if i did it correctly . I get the following issue  . I pulled yur latest changes 

```
File "pose_estimation/video.py", line 29, in <module>
    from lib.detector.mmdetection.high_api import human_boxes_get as mm_det
  File "hrnet/lib/detector/mmdetection/high_api.py", line 8, in <module>
    from mmdet.models import build_detector
  File "hrnet/lib/detector/mmdetection/mmd/mmdet/__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'mmdet.version'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

**Comment by lxy5513** [comment]
You also need 'make' in mmdet， detail please see mmdetation readme

**Comment by timtensor** [comment]
ok , it looks quite complicated to setup , because i followed the instruction . i still dotn get it up and running for some reason .  I guess since there are so many different packages and dependencies . one cannot really have a smooth installation in the early stage .But hopefully it can be used out of the box . The post error messafe i get is 
`    from .. import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda'
`
I feel at this moment is is not really out of the box detector to use right ?

**Comment by lxy5513** [comment]
I think you can first run demo.py then run deno_mmd,py, If former success and latter fail.the problem must is in mmdetection.

**Comment by timtensor** [comment]
Thank you for the tips but i am quite lost in the setup process. I seem to already get an error in running `demo.py` file.  

```
Loading network.....
Network successfully loaded
Traceback (most recent call last):
  File "pose_estimation/demo.py", line 164, in <module>
    main()
  File "pose_estimation/demo.py", line 138, in main
    bboxs, scores = yolo_det(args.img_input, human_model, confidence=0.5) # bboxes (N, 4) [x0, y0, x1, y1]
  File "/hrnet/lib/detector/yolo/human_detector.py", line 136, in human_bbox_get
    batches = list(map(prep_image, imlist, [inp_dim for x in range(len(imlist))]))
  File "hrnet/lib/detector/yolo/preprocess.py", line 41, in prep_image
    dim = orig_im.shape[1], orig_im.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'


```

**Comment by lxy5513** [comment]
Print(orig_im) it should be a array

**Comment by timtensor** [comment]
You mean an array like this ?  
I tried the following command on a test image . I think i need to give some more arguments is it ?? 

`python3.6 pose_estimation/demo.py -i test.jpeg --display` ??
Otherwise i seem to get some warning 
` warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
`
And i guess it will only work for images not video . 

```
`Loading network.....
Network successfully loaded
Loading network.....
Network successfully loaded
[[[ 58 125 224]
  [ 61 128 227]
  [ 65 132 231]
  ...
  [102 152 228]
  [116 167 240]
  [116 167 240]]

 [[ 66 133 232]
  [ 68 135 234]
  [ 71 138 237]
  ...
  [113 163 239]
  [108 158 234]
  [108 159 232]]

 [[ 75 142 241]
  [ 76 143 242]
  [ 77 144 243]
  ...
  [115 167 243]
  [102 154 230]
  [102 154 230]]
```

 I followed the instructions within the  `mmd`   and installed the dependicies and succesfully compiled them 

```
python3 setup.py install --user
PYTHON=python3.6 ./compile.sh
``
But it still complains about a checkpoint file , The printout seems to be hardcoded 

` raise IOError('{} is not a checkpoint file'.format(filename))
OSError: /ssd/xyliu/models/mmdetection/cascade_rcnn_r50_fpn_20e_20181123-db483a09.pth is not a checkpoint file


I am also trying to run the yolo module seperately but seem to get an error . Having yolo in the root folder and having the video , in the yolo root folder i try to execute 
`detector/yolo$ python3.6 video_demo.py --video test_mod.mp4 --confidence 0.5 --cfg yolov3.cfg --weights yolov3.weight`

Which leads to some error 

```
 ```
 file = open(cfgfile, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/cfg/yolov3.cfg'
```
```

If you have suggestions on how to proceed forward that would be really helpful

**Comment by lxy5513** [comment]
I am very sorry to reply you so long.


 some warning is doesn't matter, It also works in video.

 the cfgfile should in ` lib/detector/yolo/cfg/ `
