### ISSUE TITLE
no  plot_keypoint, PreProcess,yolo_det

### ISSUE THREAD

**Issue by thekoshkina** [lxy5513/hrnet#2]
from utilitys import plot_keypoint, PreProcess
from lib.detector.yolo.human_detector import main as yolo_det

utilitys and lib/detector/yolo/human_detector seem to be missing 

Can you please upload them to github?

**Comment by lxy5513** [comment]
Yes, I have alread update it.

**Comment by thekoshkina** [comment]
thanks
