### ISSUE TITLE
jupyter notebook implementation on google colab ?

### ISSUE THREAD

**Issue by basicvisual** [lxy5513/hrnet#6]
Hi , 
Is it possible to run on google colab ?  That would be great , as users might not have access to gpus in order to run the code ?

**Comment by lxy5513** [comment]
Sorry, I have not prepare to realize it in jupyter recently.

**Comment by basicvisual** [comment]
ok , thank you !!

**Comment by basicvisual** [comment]
Hello extending , your work in colab, we tried to see your model. It seems to be , detection poses some of the times and not detecting some other times. we were trying randon youtube videos to the performance.
Are there some prerequisites for the implementation . 
[(https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/HRNet_lxy5513.ipynb#scrollTo=ZPIkVY3uBqB4](url)

We tried to increase the duration of the video from default 5 seconds to 30 . Pelase let us know what are your thoughts ? 

PS - sometime the first frame is an add or just some texts in a video. I dont think that affects the video processing ? When i played around a bit it seem to look like that , the first frame should have a person , to have an reference

**Comment by lxy5513** [comment]
sorry , I don't what you mean about ` increase the duration of the video `

**Comment by basicvisual** [comment]
Hi , I mean if i increase how long the video is played for example lets say from `5 mins` to `10 mins`.  I was just curious , why in some video sequences, it fails to detect anything , even if there are people in the video streamed

**Comment by lxy5513** [comment]
the detection is based on each frame of video, every frame is independent。 it is no relevant about the duration of the video.

**Comment by lxy5513** [comment]
maybe the frame is blurry in video, which people is high speed motion , so it fails to detect anything.

**Comment by basicvisual** [comment]
Thank you ! I will play around the colab document.  While playing around , i have noticed that the `first frame` has to have a human in it. The problem before , was running videos that started with some text just blank screen. On such occasions it seems to fail . (that is just my observation) .  I will investigate more . 

Is it possible to fine tune the model ?  Perhaps a different `weight` configuration from the ones you provided ?  Its performance is good but sometimes it seems to be quite shaky.  Do you have suggestion on that ?  The default seems to be `'pose_hrnet_w48_256x192.pth`

Do you have documentation of the `keypoint` ordering ? 

 I will check with multi person keypoint detection .
