### ISSUE TITLE
Error establishing connection to servers from requirement.txt

### ISSUE THREAD

**Issue by hasu0023** [lxy5513/hrnet#7]
![hrnet_issue](https://user-images.githubusercontent.com/48244776/57966867-0df8c180-7958-11e9-8901-0b8c2598891b.png)

Can you comment, why I cannot establish communication to these channels present in requirement.txt for setting up the environment?

**Comment by lxy5513** [comment]
清华源的anaconda镜像已经不可用了， 你需要把它们删了，用官方的镜像。

**Comment by lxy5513** [comment]
I have updated the env_info_file.yml

**Comment by hasu0023** [comment]
Still I could not access other packages as you can see from image, do my system requirements needs to be modified? I do have anaconda, Python 3.7 / 3.6 installed and related packages. Maybe I am missing something, not sure. Thanks for any help.
![hrnet_env_error](https://user-images.githubusercontent.com/48244776/57969340-5921cd00-7976-11e9-91d5-79638eb0a733.png)

**Comment by lxy5513** [comment]
you can install by pip 

if you have cuda10, you can  :   
```
conda create -n hrnet python=3.7  
pip install -r requirements
cd lib && make
```  
if you have other cuda version   
you can replace pytorch in requirements, like:  
```
pip install torch==1.0.1 -f https://download.pytorch.org/whl/cu80/stable # CUDA 8.0 build
pip install torch==1.0.1 -f https://download.pytorch.org/whl/cu90/stable # CUDA 9.0 build
pip install torch==1.0.1 -f https://download.pytorch.org/whl/cu92/stable # CUDA 9.2 build
```
